import os
import shutil
import sqlite3
import requests
import json
import time
from dotenv import load_dotenv
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options

# LOAD ENV
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, "config", ".env"))

# CONFIG
CURATED_DIR = os.path.join(BASE_DIR, "content", "curated")
POSTED_DIR = os.path.join(BASE_DIR, "content", "posted")
DB_PATH = os.path.join(BASE_DIR, "database", "content.db")
DA_TOKEN_FILE = os.path.join(BASE_DIR, "config", "deviantart_tokens.json")
PATREON_LINK = os.getenv("PATREON_LINK")

# === DEVIANTART (API) ===
def load_da_token():
    try:
        with open(DA_TOKEN_FILE, "r") as f:
            tokens = json.load(f)
            return tokens.get("access_token")
    except:
        return None

def post_to_deviantart(image_path, title, tags):
    access_token = load_da_token()
    if not access_token:
        print("[DA] Error: Missing Token. Run get_deviantart_token.py")
        return False
        
    try:
        url = "https://www.deviantart.com/api/v1/oauth2/stash/submit"
        with open(image_path, 'rb') as img_file:
            data = {
                'access_token': access_token,
                'title': title,
                'artist_comments': f"Generated by Lady Nuggets AI.\n\n💜 High-Res: {PATREON_LINK}",
                'tags': ' '.join(tags),
                'is_mature': 'true' 
            }
            res = requests.post(url, data=data, files={'file': img_file})
            if res.status_code == 200:
                print(f"[DA] Posted: {title}")
                return True
            else:
                print(f"[DA] Failed: {res.text}")
                return False
    except Exception as e:
        print(f"[DA] Error: {e}")
        return False

# === TWITTER (SELENIUM) ===
def post_to_twitter(image_path, title):
    print("[X] Launching Selenium...")
    
    # Chrome Options
    chrome_options = Options()
    # chrome_options.add_argument("--headless") # Comment out for first run (Login)
    chrome_options.add_argument(f"user-data-dir={os.path.join(BASE_DIR, 'tmp', 'chrome_profile')}")
    
    try:
        driver = webdriver.Chrome(options=chrome_options)
        driver.get("https://twitter.com/compose/tweet")
        time.sleep(5) # Wait for load
        
        # Check if logged in (Look for 'Log in' button or similar)
        if "login" in driver.current_url:
            print("[X] PLEASE LOG IN MANUALLY within 60 seconds...")
            time.sleep(60)
            
        # Upload
        file_input = driver.find_element(By.CSS_SELECTOR, "input[type='file']")
        file_input.send_keys(os.path.abspath(image_path))
        time.sleep(2)
        
        # Text
        text_area = driver.find_element(By.CSS_SELECTOR, "div[data-testid='tweetTextarea_0']")
        text_area.click()
        text_area.send_keys(f"{title} 💜 #AIArt #Anime\n\nFull: {PATREON_LINK}")
        time.sleep(1)
        
        # Post
        post_btn = driver.find_element(By.CSS_SELECTOR, "div[data-testid='tweetButton']")
        post_btn.click()
        
        print(f"[X] Posted: {title}")
        time.sleep(5)
        driver.quit()
        return True
        
    except Exception as e:
        print(f"[X] Selenium Error: {e}")
        return False

def main():
    # Pick Image
    # (Simplified selection logic for brevity)
    premium_dir = os.path.join(CURATED_DIR, "premium")
    if not os.path.exists(premium_dir): return
    
    files = [f for f in os.listdir(premium_dir) if f.endswith(".png")]
    if not files:
        print("No images to post.")
        return
        
    img_path = os.path.join(premium_dir, files[0])
    title = f"Daily Drop {files[0]}"
    tags = ["aiart", "anime"]
    
    # Execute
    res_da = post_to_deviantart(img_path, title, tags)
    res_tw = post_to_twitter(img_path, title)
    
    if res_da or res_tw:
        shutil.move(img_path, os.path.join(POSTED_DIR, files[0]))
        print(f"Moved {files[0]} to Posted.")

if __name__ == "__main__":
    main()
